### ISSUE TITLE
Table truncates columns at certain viewport widths

### ISSUE THREAD

**Issue by nickjevershed** [guardian/interactive-table-builder#1]
eg using [rugby table](http://www.theguardian.com/sport/blog/2015/sep/07/rugby-world-cup-preview-australia-team-guide) columns are truncated with no scrollbar showing up. 

![screen shot 2015-09-09 at 4 16 41 pm](https://cloud.githubusercontent.com/assets/4686066/9754631/8967dde4-570e-11e5-89d6-dd0ae4cc738c.png)

**Comment by holder-josh** [comment]
@nickjevershed no perfect fix for responsive tables, but the table can now scroll if it overflows.
