### ISSUE TITLE
Table sorting doesn't sort decimals correctly

### ISSUE THREAD

**Issue by nickjevershed** [guardian/interactive-table-builder#2]
Sorting treats all 0.XXX decimals as zero, I think. 

[Example Table](https://interactive.guim.co.uk/tools/tables/embed/index.html?spreadsheet=1QYai82t4gB_UkLqJ_GssSdrqA6oxocgVSi3_bbQOjdY)

![screen shot 2015-09-09 at 4 25 34 pm](https://cloud.githubusercontent.com/assets/4686066/9754798/c25836fc-570f-11e5-97a2-d52e393a6f6f.png)

**Comment by holder-josh** [comment]
Hi @nickjevershed, I've just pushed a fix for this. Seems to work great now.
